#!/bin/bash -x
read -p "Enter a number : " num
if test $((num % 2)) -eq 0 -a $((num % 3)) -eq 0
then
	echo "The number $num is divisible by both"
elif test $((num % 2)) -eq 0
then
	echo "The number $num is divisible by 2 only"
elif test $((num % 3)) -eq 0
then
	echo "The number $num is divisible by 3 only"
else
	echo "The number is not divisible by both"
fi

