#!/bin/bash
echo -n "Even numbers : "
for((i=1;i<=100;i++))
do
	if test $((i%2)) -eq 0
	then
		echo -n "$i "
	fi
done
echo
echo -n "Odd numbers : "
for((i=1;i<=100;i++))
do
	if test $((i%2)) -ne 0
	then
		echo -n "$i "
	fi
done 
echo 
